name: Deploy VEMU to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Build WASM
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Stage site
        run: |
          mkdir -p site

          cp target/wasm32-unknown-unknown/release/veewasm.wasm .

          cp index.html help.md run.sh README.md veewasm.wasm site/

          cp -r js site/
          cp -r css site/
          cp -r freecpm site/

          # Copy documentation and images
          cp -r docs site/

          #copy page icon
          cp vemu-icon.png site/

          # Disable Jekyll processing
          touch site/.nojekyll

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4